### ISSUE TITLE
Use igpu for some apps

### ISSUE THREAD

**Issue by chenxiex** [ewagner12/all-ways-egpu#10]
Is it possible to use igpu for some apps when using egpu to render the DE? Some apps work bad with egpu.

**Comment by ewagner12** [comment]
You can try using the DRI_PRIME=1 environment variable. Doing `DRI_PRIME=1 some_app` tells some_app to use the secondary GPU, so that would use the iGPU when using this script. The performance might improve or might not improve. It depends on how your desktop handles copying data between the GPUs and scanning out to the screen. Since it is different between different desktop environments and applications you might have to try different things to see what works for you, I don’t think there’s anything I can do in the script to fix this.
