### ISSUE TITLE
No card set as primary

### ISSUE THREAD

**Issue by Smeeto13** [ewagner12/all-ways-egpu#12]
On arch linux with systemd and KDE with SDDM:
Booting the laptop with the gpu connected, checking the systemd log for all-ways-egpu-set-compositor.service says "No card set as primary" restarting the service with systemctl causes the eGPU to be detected and the variables set, the problem is not present if using no auth thunderbolt setting in system bios so I assume the problem is due to a delay in the eGPU being detected after authorisation? how can I resolve this so I can avoid using "ctrl + alt + f3" to switch to the tty and restarting the service manually

**Comment by ewagner12** [comment]
Hi @Smeeto13 

You're correct that timing can be an issue with a slight delay before the eGPU is initialized and seen as a GPU that can be used by the system. Some systems allow thunderbolt during bootup and others don't allow it until the linux kernel starts. Sometimes this can be changed as a bios option called "Allow Thunderbolt in Pre-boot" or something like that.

Since every laptop is slightly different could you post the exact model of the laptop and eGPU you're using? Then I'll look into seeing if there's something I can do to fix this for you.

**Comment by Smeeto13** [comment]
I'm using a Dell latitude 7290, I don't want to enable preboot support in the bios as it bypasses the security modes, I'll look into it more myself when I get a chance but I'm busy with coursework at the minute

**Comment by ewagner12** [comment]
I would like to avoid assuming there is an enclosure since the script may be used with an M.2 eGPU or other setups where there's no enclosure. I'd also rather not add arbitrary delays to the script.

Looking at the way other scripts have handled this, I think the best way would be to add logic where if the eGPU is not found then the script can loop back and "retry" to find the eGPU again after a short delay up to a certain user configurable number of times. I'd probably set it to something low like 1-2 by default but you could adjust it as high as needed in your case. If that sounds like it would work for you then I can try and add it to the script.

**Comment by ewagner12** [comment]
@Smeeto13 
I updated the script with the changes mentioned above. When you have time, could you try and install the latest [github](https://github.com/ewagner12/all-ways-egpu#git) version and see if it fixes the problem.

**Comment by Smeeto13** [comment]
Great, thanks, I'll have time to test it on Tuesday
