### ISSUE TITLE
OpenRC support?

### ISSUE THREAD

**Issue by RefinedAnarchy** [ewagner12/all-ways-egpu#2]
This program currently only works with systemd, are there any plans to add openrc support in the future?

**Comment by ewagner12** [comment]
Hi @RefinedAnarchy,

Thanks for the issue. Just to be clear, only the parts of the script that run at boot and login depend on systemd so you can still use the commands `all-ways-egpu switch egpu` or `all-ways-egpu set-boot-vga egpu` to try and switch each time after you startup. I am definitively looking to make Method 2 no longer rely on systemd in a future update. I think this bind mount process could just be done in /etc/fstab instead of lazily relying on a systemd service.

Unfortunately, I can't make any promises to fully support a specific init system right now, but this script is still in development and PR's are always welcome.

**Comment by ewagner12** [comment]
After looking more into this, I think I should be able to switch over to init-style scripts that should hopefully work for everyone, so I will try and add this in a future update.

**Comment by ewagner12** [comment]
I just posted commit ac859b9a0fcc9e0f50a4e1f513e669a9be1f145e
This includes changes that will hopefully support OpenRC.
Try out the latest git code and let me know if this works out for you.

**Comment by ewagner12** [comment]
@RefinedAnarchy 
OpenRC support now should work with the latest 0.31 release. I tested with Devuan with OpenRC and it is working for me. Do note the issue stated near the end of the README where you might have to initially link xdm or whatever init script is starting your display manager. I'm closing this issue now, but feel free to open another if you encounter any problems or bugs.
